default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: fb3_development

test:
  <<: *default
  database: fb3_test

staging:
  <<: *default
  socket: /var/run/mysqld/mysqld.sock
  database: fb3_staging
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>

production:
  <<: *default
  socket: /var/run/mysqld/mysqld.sock
  database: fb3_production
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
